name: CI

on:
  push:
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          pip install black==23.9.1 flake8==6.0.0

      - name: Run pytest
        run: pytest -vv

      - name: Run Black
        run: black --check .

      - name: Run Flake8
        run: flake8

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Node dependencies
        run: |
          npm ci
          npm ci --prefix frontend

      - name: Run ESLint
        run: npx eslint .
